<header>
    <article>
        <div class="logo">
            <a href="index.php"><img src="assets/images/logo.svg" alt="Realtime CVs"></a>
        </div>
        <div class="navigation">
            <nav>
                <ul>
                    <li class="fitstnav"><a href="index.php">Admin Dashboard</a></li>
                    <li><a href="templates.php">Templates</a></li>
                    <li><a href="payments.php">Invoices/Payments</a></li>
                    <li><a href="controller/logout.php">Logout</a></li>
                </ul>
            </nav>
        </div>
        <div class="clearfix"></div>
    </article>
</header>