<div class="sidebar">
    <div class="sidenav">
            <a href="index.php"><div class="link"><i class="fa-solid fa-house"></i><br />Dashboard</div></a>
    </div>
    <div class="sidenav">
            <a href="cv-templates.php"><div class="link"><i class="fa-solid fa-chalkboard-user"></i><br />Resumes</div></a>
    </div>
    <div class="sidenav">
            <a href="cl-templates.php"><div class="link"><i class="fa-solid fa-envelope-open-text"></i><br />Cover Letters</div></a>
    </div>
</div>