<header>
    <article>
        <div class="logo">
            <a href="index.php"><img src="assets/images/logo.svg" alt="Realtime CVs"></a>
        </div>
        <div class="navigation">
            <nav>
                <ul>
                    <li class="fitstnav"><a href="about.php">About</a></li>
                    <li><a href="#">Documentation</a></li>
                    <li><a href="#">pricing</a></li>
                    <li class="lastnav"><a href="login.php">Signin/Register</a></li>
                </ul>
            </nav>
        </div>
        <div class="clearfix"></div>
    </article>
</header>