<header>
    <article>
        <div class="logo">
            <a href="index"><img src="assets/images/logo.svg" alt="Realtime CVs"></a>
        </div>
        <div class="navigation">
        <input class="side-menu" type="checkbox" id="side-menu"/>
        <label class="hamb" for="side-menu"><span class="hamb-line"></span></label>
            <nav>
                <ul>
                    <li class="fitstnav"><a href="about">About</a></li>
                    <li><a href="#">Documentation</a></li>
                    <li><a href="pricing">pricing</a></li>
                    <li class="lastnav"><a href="login">Signin/Register</a></li>
                </ul>
            </nav>
        </div>
        <div class="clearfix"></div>
    </article>
</header>