<header>
    <article>
        <div class="logo">
            <a href="#"><img src="assets/images/logo.svg" alt="Realtime CVs"></a>
        </div>
        <div class="navigation">
            <nav>
                <ul>
                    <li class="fitstnav"><a href="#">My profile</a></li>
                    <li><a href="#">Logout</a></li>
                </ul>
            </nav>
        </div>
        <div class="clearfix"></div>
    </article>
</header>