<div class="sidebar">
    <div class="sidenav">
            <a href="home.php"><div class="link"><i class="fa-solid fa-house"></i><br />Dashboard</div></a>
    </div>
    <div class="sidenav">
            <a href="cv.php"><div class="link"><i class="fa-solid fa-chalkboard-user"></i><br />My CV</div></a>
    </div>
    <div class="sidenav">
            <a href="coverletter.php"><div class="link"><i class="fa-solid fa-envelope-open-text"></i><br />Cover Letter</div></a>
    </div>
</div>