<footer> 
    <div class="whatsappicon"><a href="https://wa.me/+254793632263" target="_new" title="Open Talent"><img src="assets/images/whatsappicon.svg" alt="whatsapp"></a></div>
    <article>
        <div class="row">
            <div class="col-lg-12">
                <p>Get In touch: <a href="tel:+254742120670">+254 (0) 742120670</a> / <a href="+254793632263">+254 (0) 793632263</a><br /> Email: <a href="mailto:cvrevamp@opentalentafrica.com">cvrevamp@opentalentafrica.com</a> | <a href="mailto:support@opentalentafrica.com">support@opentalentafrica.com</a></p>
            </div>
        </div>
        <div class="copy">&copy;2022 Open Talent Africa | Developed by <a heref="danneconsult.com" target="_new">Danne Consult Ltd</a></div>
    </article>
</footer> 